default: &default
  adapter: postgresql
  encoding: unicode
  username: wormer
  password: Wormer123
  database: blog_app
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  password: <%= ENV['BLOG_DATABASE_PASSWORD'] %>
